### ISSUE TITLE
Issue with valid card number (according to Luhn) but unknown vendor

### ISSUE THREAD

**Issue by intrueder** [surveyor666/CreditCardNumber#5]
Vendor for `35301113333000001` has been recognized as `Unknown` (correct, 17 digits instead of 16 for JCB)
Such number should not pass validation, but it passes.

**Comment by elder-sigma** [comment]
As I understood, I have to change IsCreditCardNumberValid function to return false if there is no possible vendors for current credit card number.

**Comment by intrueder** [comment]
> return false if there is no possible vendors for current credit card number

correct
